name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clone Blowfish theme
        run: |
          mkdir -p themes
          git clone https://github.com/nunocoracao/blowfish.git themes/blowfish --depth 1

      - name: Install Hugo extended
        run: |
          HUGO_VERSION=${{ secrets.HUGO_VERSION }}
          wget -q "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz"
          tar -xzf "hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz"
          sudo mv hugo /usr/local/bin/hugo
          hugo version

      - name: Build Hugo site
        run: hugo --minify

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
          cname: gainsonadime.com
